

let suggestions = [
    "Anohana",
    "A silent voice",
    "Akame ga kill",
    "Banana Fish",
    "Black clover",
    "Bakemonogatari",
    "Erase",
    "Elfen lied",
    "Naruto",
    "Bleach",
    "Revenge no kun",
    "My hero academia",
    "One punch man",
    "Dragon ball z",
    "Gintama",
    "Highschool DxD",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to became Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];